# Generated by Django 5.2 on 2026-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
